atm/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('machine.urls',namespace='machine'))
]

machine/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^pincode$',views.pin,name='pincode'),
        url(r'^main$',views.main,name='main'),
        url(r'^exit$',views.exit,name='exit'),
        url(r'^balance$',views.balance,name='balance'),
        url(r'^withdraw$',views.withdraw,name='withdraw'),
        url(r'^$',views.index,name='index')
        
        ]

machine/models.py
from django.db import models

class Account(models.Model):
    account_num = models.CharField(max_length=16)
    pin = models.CharField(max_length=32)
    block_flag = models.BooleanField()
    balance = models.FloatField()

class AccessLog(models.Model):
    RESULT_CODES = [ (0,'Access Granted'),\
            (1,'Access Denied'),(2,'Access Blocked')]
    account = models.ForeignKey(Account,on_delete=models.CASCADE)
    result = models.IntegerField(choices = RESULT_CODES)
    timestamp = models.DateTimeField(auto_now_add=True)

class OperationLog(models.Model):
    account = models.ForeignKey(Account,on_delete=models.CASCADE)
    withdraw_summ = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    opcode = models.CharField(max_length=2)

machine/forms.py
from django import forms

from machine.models import Account

class AccountLogin(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['account_num']

class PinForm(forms.Form):
    pin = forms.CharField(max_length=4)

class AmmountForm(forms.Form):
    amount = forms.IntegerField()

machine/views.py
import hashlib
from django.shortcuts import render,redirect
from machine.models import Account, AccessLog, OperationLog
from machine.forms import AccountLogin,PinForm,AmmountForm
from django.views.decorators.csrf import csrf_protect
from machine.utils import account_required,pin_required

@csrf_protect
def index(request):
    val = AccountLogin(request.POST)
    if request.method == 'POST':
        if val.is_valid():
            acc = Account.objects.filter(\
                    account_num=val.cleaned_data['account_num']).count()
            if acc>0:
                acc_inst = Account.objects.get(\
                    account_num=val.cleaned_data['account_num'])

                if acc_inst.block_flag:
                    access = AccessLog(account=acc_inst,result=2)
                    access.save()
                    return render(request,'machine/error.html')
                else:
                    request.session['acc']=val.cleaned_data['account_num']
                    return redirect('machine:pincode')
            else:
                return render(request,'machine/error.html')
        else:
            return render(request,'machine/error.html')
    return render(request,'machine/index.html',{'form':val})
    
@csrf_protect
@account_required
def pin(request):
    val = PinForm(request.POST)
    if request.method == 'POST':
        if val.is_valid():
            acc = Account.objects.get(\
                    account_num=request.session['acc'])
            if acc.block_flag:
                access = AccessLog(account=acc,result=2)
                access.save()
                return render(request,'machine/error.html')

            digest = hashlib.md5()
            digest.update(val.cleaned_data['pin'].encode('UTF-8'))
            tm=digest.hexdigest()

            if acc.pin == tm:
                access = AccessLog(account=acc,result=0)
                access.save()
                request.session['acc_pin']=acc.pin

                return redirect('machine:main')
            else:
                access = AccessLog(account=acc,result=1)
                access.save()
                access_log = AccessLog.objects.filter(account=acc)[::-1][:4]
                if all(filter(lambda x: x.result in [1,2],access_log)):
                    acc.block_flag=True
                    acc.save()
                    access = AccessLog(account=acc,result=2)
                    access.save()
                    return render(request,'machine/error.html')
                else:    
                    return render(request,'machine/pin.html',{'form':val})
        else:
            return render(request,'machine/error.html')
 
    return render(request,'machine/pin.html',{'form':val})

@account_required
@pin_required
def main(request):
    return render(request,'machine/main.html')

@account_required
@pin_required
def exit(request):
    del request.session['acc']
    del request.session['acc_pin']
    return redirect('machine:index')

@csrf_protect
@account_required
@pin_required
def withdraw(request):
    val = AmmountForm(request.POST)

    if request.method == "POST":
        if val.is_valid():
            acc = Account.objects.get(account_num=request.session['acc'])
            if 0< val.cleaned_data['amount']<acc.balance:
                acc.balance -= val.cleaned_data['amount']
                acc.save()
                op = OperationLog(account = acc,\
                        withdraw_summ =val.cleaned_data['amount'],opcode='wd')
                op.save()
                return render(request, 'machine/success.html')
            else:
                return render(request,'machine/error.html')

        else:
            return render(request,'machine/error.html')


    return render(request,'machine/withdraw.html',{'form':val})

    

@account_required
@pin_required
def balance(request):
    acc = Account.objects.get(account_num=request.session['acc'])
    op = OperationLog(account = acc,withdraw_summ=0,opcode='bl')
    op.save()
    return render(request,'machine/status.html',{'result':acc})

machine/templates/machine/error.html
<h2>Error</h2>

machine/templates/machine/index.html
{% extends 'machine/layout.html' %}


{% block title %} Insert card {% endblock %}
{% block content %}
Enter card number
<form method="POST" action="{% url 'machine:index' %}">
	{% csrf_token %}
	{{ form.as_table }}
	<input type="submit" value="submit">
</form>
<script type="text/javascript">
			
$(document).ready(function(){
								
	$('#id_account_num').numpad({
		//displayTpl: '<input class="form-control" type="password" />',
		hidePlusMinusButton: true,
		hideDecimalButton: true	
	});
												
});
</script>
{% endblock %}

machine/templates/machine/layout.html
 {% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
		<script src="{% static 'machine/jquery.numpad.js' %}"></script>
		<link rel="stylesheet" href="{% static 'machine/jquery.numpad.css' %}">
		 <title>{% block title %}ATM{% endblock %}</title>
	</head>
	<body>
		{% block content %}{% endblock %}
	</body>
</html>

machine/templates/machine/main.html
{% extends 'machine/layout.html' %}


{% block title %} Menu{% endblock %}
{% block content %}


<a href="{% url 'machine:exit' %}">Exit</a><br>
<a href="{% url 'machine:withdraw' %}">Withdraw</a><br>
<a href="{% url 'machine:balance' %}">Balance</a>
{% endblock %}

machine/templates/machine/pin.html
{% extends 'machine/layout.html' %}


{% block title %} Enter pin{% endblock %}
{% block content %}

<form method="POST" action="{% url 'machine:pincode' %}">
	{% csrf_token %}
	{{ form.as_table }}
	<input type="submit" value="submit">
</form>
<script type="text/javascript">
			
$(document).ready(function(){
								
	$('#id_pin').numpad({
		displayTpl: '<input class="form-control" type="password" />',
		hidePlusMinusButton: true,
		hideDecimalButton: true	
	});
												
});
</script>
{% endblock %}

machine/templates/machine/status.html
{% extends 'machine/layout.html' %}


{% block title %} Card Balance{% endblock %}
{% block content %}


Current balance: {{result.balance}}<br>
<a href="{% url 'machine:exit' %}">Exit</a><br>
<a href="{% url 'machine:main' %}">Menu</a>
{% endblock %}

machine/templates/machine/success.html
{% extends 'machine/layout.html' %}


{% block title %} Money withdrawn{% endblock %}
{% block content %}
<h2>Take money!</h2>
<a href="{% url 'machine:exit' %}">Exit</a><br>
<a href="{% url 'machine:balance' %}">Balance</a>
{% endblock %}

machine/templates/machine/withdraw.html
{% extends 'machine/layout.html' %}


{% block title %} Withdraw{% endblock %}
{% block content %}


<h2> Enter withdraw amount:</h2>
<form method="POST" action="{% url 'machine:withdraw' %}">
	{% csrf_token %}
	{{ form.as_table }}
	<input type="submit" value="submit">
</form>
<script type="text/javascript">
			
$(document).ready(function(){
								
	$('#id_amount').numpad({
		//displayTpl: '<input class="form-control" type="password" />',
		hidePlusMinusButton: true,
		hideDecimalButton: true	
	});
												
});
</script>
{% endblock %}